name: "2. Infra and Deploy"

on:
  workflow_run:
    workflows: ["1. Build and Push"]
    types: [completed]
  workflow_dispatch: # Allows you to run this manually if you just want to update infra

jobs:
  terraform-and-deploy:
    runs-on: ubuntu-latest
    # Only run if the build pipeline actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply (Create ECS/EC2)
        working-directory: ./infra
        run: |
          terraform init -upgrade
          terraform apply -auto-approve

      - name: Force ECS Deployment
        run: |
          # This tells ECS to pull the latest image we just pushed in Pipeline 1
          apps=("app-nginx" "app-python" "app-nodejs")
          for app in "${apps[@]}"; do
            aws ecs update-service --cluster my-app-cluster --service $app --force-new-deployment
          done
